name: Build & Push

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# cancel workflow if there is already one running
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.0.0
      - name: Set up JDK 17
        uses: actions/setup-java@v3.0.0
        with:
          java-version: 17
          distribution: liberica
      - name: Build plugin
        run: ./gradlew buildPlugin
        working-directory: ide-former-plugin

  # build docker container
  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.0.0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
          platforms: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' && 'linux/amd64,linux/arm64' || 'linux/amd64' }}
          tags: ghcr.io/${{ github.repository }}/runner:latest,ghcr.io/${{ github.repository }}/runner:${{ github.sha }}
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}/runner:latest




